name: FixerBedWars1058
version: 1.0.0
main: me.stefan923.fixerbedwars1058.FixerBedWars1058
description: Adds a fully customizable flight system to Minecraft.
softdepend: [BedWars1058]
authors: [Stefan923]
